# .goreleaser.yml
version: 2
project_name: agon
before:
  hooks:
    - go mod tidy
    - go test ./...
builds:
  # Build 1: "agon"
  - id: "agon"
    # 'main' is a key specifying the entrypoint path
    main: ./cmd/agon/main.go
    binary: agon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64

  # Build 2: "agon-mcp"
  - id: "agon-mcp"
    # 'main' is used again for the second binary's entrypoint
    main: ./mcp/main.go
    binary: agon-mcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      
release:
  github:
    owner: mwiater
    name: agon
  draft: false
  prerelease: false
  name_template: "{{ .ProjectName }} v{{ .Version }}"
changelog:
  use: git
upx:
  - enabled: true
    compress: best
    lzma: true
